export const enum TrainingCommentCommands {
    SUCCESS_ADDED_COMMENT = 'SUCCESS_ADDED_COMMENT',
    ERROR_ADDED_COMMENT = 'ERROR_ADDED_COMMENT',
    ENABLE_FIELD_DIMMER = 'ENABLE_FIELD_DIMMER',
    DISABLE_FIELD_DIMMER = 'DISABLE_FIELD_DIMMER',
    ENABLE_VIEW_DIMMER = 'ENABLE_VIEW_DIMMER',
    DISABLE_VIEW_DIMMER = 'DISABLE_VIEW_DIMMER'
}
