export class ErrorLabelsModel {
    constructor(
        public LOAD_POST_ERROR_MSG = 'Ошибка, загрузка постов не удалась!',
        public LOAD_USER_DATA_ERROR_MSG = 'Ошибка, не удалось загрузить данные о пользователе!',
        public USER_LOGOUT_ERROR = 'Ошибка, выход не выполнен!',
        public LOAD_MESSAGES_ERROR = 'Ошибка, не удалось получить список сообщений!',
        public NO_RELATED_USERS_ERROR = 'У вас нет связей с пользователями, отправка сообщения невозможна',
        public ERROR_WHEN_MESSGE_SENDING = 'Поля заполнены некорректно',
        public ERROR_SENDING_MESSAGE = 'Отправка сообщения не удалась',
        public ERROR_DELETING_MESSAGE = 'Удаление сообщения не удалось',
        public ERROR_COMPLETING_MICROCILE = 'При завершении микроцикла произошел сбой, попробуйте позже!',
        public ERROR_DELETING_MICROCICLE = 'Ошибка соединения с сервером, микроцикл не удалось удалить!',
        public TR_TRAINING_NAME_MUST_BE_SPECIFIED  = 'Поле имени тренировки должно быть заполнено!',
        public TR_ERROR_MODAL_MESSAGE = 'Упс... что то пошло не так...',
        public ALL_FIELDS_MUST_BE_SPECIFIED = 'Все поля должны быть заполнены',
        public STD_HTTP_LOAD_ERROR = 'Ошибка соединения с сервером, данные не загружены!',
        public STD_HTTP_SEND_ERROR = 'Ошибка соединения с сервером, данные не отправлены!',
        public EXERCISE_ALREADY_EXISTS_IN_LAYOUT = 'Упражнение уже добавлено в шаблон',
        public ERROR_DELETING_COMMENT = 'Ошибка соединения с сервером, не удалось удалить коментарий',
        public ERROR_ADDING_COMMENT = 'Ошибка соединения с сервером, не удалось добавить кометарий!',
        public CREATE_TP_ERROR_MSG_1 = 'Для тренировочного плана должны быть выбраны упражнения',
        public CREATE_TP_ERROR_MSG_2 = 'Название тренировочного плана должно быть указано',
        public CREATE_TP_ERROR_MSG_3 = 'Тренировочному плану должна быть назначена видимость',
        public CREATE_TP_ERROR_MSG_4 = 'Тренировочному плану должна быть назначена категория',
        public ADDING_ERROR_MESSAGE = 'Перед добавлением нужно выбрать упражнение',
        public LOGIN_USER_NOT_FINDED = 'Указаная комбинация имени и пароля не найдена',
        public LOGIN_USERNAME_FIELD_EMPTY = 'Поле логина не заполнено',
        public LOGIN_PASSWORD_FIELD_EMPTY = 'Поле пароля не заполнено',
        public REGISTRATION_USER_ALREADY_EXISTS = 'Пользователь с таким логином уже существует',
        public REGISTRATION_EMPTY_LOGIN_FIELD = 'Поле логина не заполнено',
        public REGISTRATION_EMPTY_EMAIL_FIELD = 'Поле электронной почты заполнено некоректно',
        public REGISTRATION_EMPTY_PASSWORD_FIELD = 'Поле пароля не заполнено',
        public REGISTRATION_PASSWORDS_DONT_EQUAL = 'Пароли не совпадают'
    ) {}
}
