export class Dates {
    constructor(
    public oneMinuteAgo = 60,
    public fiveMinuteAgo = oneMinuteAgo * 5,
    public tenMinuteAgo = oneMinuteAgo * 10,
    public fiveteenMinuteAgo = fiveMinuteAgo * 3,
    public oneHourAgo = oneMinuteAgo * 60,
    public twoHourAgo = oneHourAgo * 2,
    public threeHourAgo = oneHourAgo * 3,
    public fourHourAgo = oneHourAgo * 4,
    public fiveHourAgo = oneHourAgo * 5,
    public sixHourAgo = oneHourAgo * 6,
    public sevenHourAgo = oneHourAgo * 7,
    public eightHourAgo = oneHourAgo * 8,
    public nineHourAgo = oneHourAgo * 9,
    public tenHourAgo = oneHourAgo * 10,
    public elevenHourAgo = oneHourAgo * 11,
    public twelveHourAgo = oneHourAgo * 12,
    public thirteenHourAgo = oneHourAgo * 13,
    public fourteenHourAgo = oneHourAgo * 14,
    public fiveTeenHourAgo = oneHourAgo * 15,
    public sixTeenHourAgo = oneHourAgo * 16,
    public seventeenHourAgo = oneHourAgo * 17,
    public eightteenHourAgo = oneHourAgo * 18,
    public nineteenHourAgo = oneHourAgo * 19,
    public twentyHourAgo = oneHourAgo * 20,
    public twentyoneHourAgo = oneHourAgo * 21,
    public twentytwoHourAgo = oneHourAgo * 22,
    public twentythreeHourAgo = oneHourAgo * 23,
    public yesterday = oneHourAgo * 24,
    public twoDayAgo = yesterday * 2,
    public threeDayAgo = yesterday * 3,
    public fourDayAgo = yesterday * 4,
    public fiveDayAgo = yesterday * 5,
    public sixDayAgo = yesterday * 6,
    public oneWeekAgo = yesterday * 7,
    public twoWeekAgo = oneWeekAgo * 2
    ) {}
}
